 # STIG Manager behind Proxy with DNS Hostname
version: '3.7'
networks:
  default:
    name: stigman-orchestration_default
    external: false
services:
  nginx:
    image: gsil-docker1.idm.example.org:5000/nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - /var/docker/stigman/logs:/var/log/nginx
      - ./certs/localhost/gsil-docker2-chain.crt:/etc/nginx/localhost.crt
      - ./certs/localhost/gsil-docker2.key:/etc/nginx/localhost.key
      - ./certs/dod/ipa-ca.crt:/etc/nginx/ipa-ca.crt
    ports:
    - "443:443"
    restart: unless-stopped
  auth:
    image: gsil-docker1.idm.example.org:5000/stig-manager-auth:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
      - KC_PROXY=edge
      - KC_HOSTNAME=stigman.idm.example.org
      - KC_HOSTNAME_ADMIN_URL=https://stigman.idm.example.org/kc/
#      - KC_SPI_X509CERT_LOOKUP_PROVIDER=nginx  ## Disabled as CAC auth is not being used
#      - KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT=SSL-CLIENT-CERT  ## Disabled as CAC auth is not being used
      - KC_SPI_TRUSTSTORE_FILE_FILE=/tmp/truststore.p12
      - KC_SPI_TRUSTSTORE_FILE_PASSWORD=password
    command: start --import-realm
    volumes:
      - ./certs/dod/truststore.p12:/tmp/truststore.p12
      - ./kc/stigman_realm.json:/opt/keycloak/data/import/stigman_realm.json
      - ./kc/h2:/opt/keycloak/data/h2/
  db:
    image: gsil-docker1.idm.example.org:5000/mysql8:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_PASSWORD=stigmanpw
      - MYSQL_DATABASE=stigman
    cap_add:
      - SYS_NICE  # workaround MySQL logging bug => mbind: Operation not permitted
    command: --innodb_buffer_pool_size=512M --sort_buffer_size=128M
    volumes:
      - ./mysql-data:/var/lib/mysql
  stigman:
    image: gsil-docker1.idm.example.org:5000/stig-manager:1.3.10
    environment:
      - STIGMAN_OIDC_PROVIDER=http://auth:8080/realms/stigman
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://stigman.idm.example.org/realms/stigman  
      - STIGMAN_CLASSIFICATION=S
      - STIGMAN_DB_HOST=db
      - STIGMAN_DB_PASSWORD=stigmanpw
      - STIGMAN_DB_USER=stigman
    init: true
    depends_on: 
    - auth
